name: Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force publish even if no changesets exist'
        required: false
        default: false
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun run test

      - name: Check for changesets
        id: check-changesets
        run: |
          if ls .changeset/*.md >/dev/null 2>&1 && [ $(ls .changeset/*.md | grep -v README.md | wc -l) -gt 0 ]; then
            echo "has-changesets=true" >> $GITHUB_OUTPUT
            echo "Found changesets to process"
          else
            echo "has-changesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found"
          fi

      - name: Exit if no changesets (unless forced)
        if: steps.check-changesets.outputs.has-changesets == 'false' && inputs.force != true
        run: |
          echo "No changesets found and force is not enabled. Exiting."
          exit 1

      - name: Version packages
        if: steps.check-changesets.outputs.has-changesets == 'true' || inputs.force == true
        run: bun run changesets:version

      - name: Commit version changes
        if: steps.check-changesets.outputs.has-changesets == 'true' || inputs.force == true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: version packages"
            git push
          fi

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: steps.check-changesets.outputs.has-changesets == 'true' || inputs.force == true
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: bun run changesets:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Releases
        if: steps.changesets.outputs.published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[] | @base64' | while read package; do
            decoded=$(echo $package | base64 --decode)
            name=$(echo $decoded | jq -r '.name')
            version=$(echo $decoded | jq -r '.version')
            
            # Extract changelog for this specific package from CHANGELOG.md
            changelog_file="packages/${name#*/}/CHANGELOG.md"
            if [ -f "$changelog_file" ]; then
              # Extract the latest version's changelog (between the first ## and the second ##)
              changelog=$(sed -n "/## $version/,/## /p" "$changelog_file" | sed '$d' | tail -n +2)
              if [ -z "$changelog" ]; then
                # Fallback: get everything after the first ## until the next ## or end of file
                changelog=$(sed -n '/^## /,/^## /p' "$changelog_file" | sed '$d' | tail -n +2)
              fi
            else
              changelog="Release of ${name} version ${version}"
            fi
            
            # Create release for each published package
            gh release create "${name}@${version}" \
              --title "${name} v${version}" \
              --notes "${changelog:-Release of ${name} version ${version}}"
          done
